--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: train-schedule
  name: train-schedule-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: train-schedule
  template: 
    metadata: 
      labels: 
        app: train-schedule
    spec: 
      containers: 
        - 
          image: "$DOCKER_IMAGE_NAME:$BUILD_NUMBER"
          name: train-schedule
--- 
apiVersion: v1
kind: Service
metadata: 
  name: train-schedule-service
spec: 
  ports: 
    - 
      nodePort: 30001
      port: 8080
      protocol: TCP
  selector: 
    app: train-schedule
  type: NodePort
