--- 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  selector:
    matchLabels:
      app: train-schedule
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: train-schedule
        tier: backend
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regsecret

--- 
kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30001
