--- 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  selector:
    matchLabels:
      app: train-schedule
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: train-schedule
        tier: backend
    spec:
      containers:
      - name: train-schedule
        image: {$DOCKER_IMAGE_NAME:$BUILD_NUMBER}
      imagePullSecrets:
      - name: regsecret
        ports:
        - containerPort: 8080
          name: train-schedule
--- 
apiVersion: v1
kind: Service
metadata: 
  name: train-schedule-service
spec: 
  ports: 
    - 
      nodePort: 30001
      port: 8080
      protocol: TCP
  selector: 
    app: train-schedule
  type: NodePort
